server:
  port: 8080
  shutdown: graceful

spring:
  application:
    name: expression-evaluator
  datasource:
    url: jdbc:h2:mem:mydb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: false
    open-in-view: false
  liquibase:
    change-log: classpath:/db/changelog-master.xml